### ISSUE TITLE
Where should we start?

### ISSUE THREAD

**Issue by MFernflower** [OpenSourceMycetoma/Series-3-Phenothiazines#2] opened 2018-11-19 16:36 UTC
A Canadian company known as Toronto Research Chemicals offers a selection of ready made phenothiazines and it appears they offer international shipping!

Below is a list of compounds I feel might be worth screening and there respective prices:

H297413 10-hexylphenothiaizne 10 mg for 40 USD (currently out of stock)
P318060  phenothiazine-10-propionitrile 50 mg for 110 USD (in stock)
M264955 10-(4-Methoxyphenyl)-10H-phenothiazine 100 mg for 45 USD (currently out of stock)
M304525 10-[2-(2-Methoxyethoxy)ethyl]-10H-phenothiazine 1 gram for 80 USD  (currently out of stock)
M326370 α-Methyl-phenothiazine-10-ethanol 100 mg for 150 USD (in stock)
P811230 N-Propionyl Phenothiazine 500 mg for 65 USD (in stock)

Phenothiazines approved or once approved for use in human OR livestock medicine:

C424750 Chlorpromazine HCL 10 grams for 65 USD (in stock)
P755790 Prochlorperazine 25 mg for 170 USD (in stock)
P475190 Pipamazine 100 mg for 75 USD (in stock)

Dr. Chris Swain @drc007 recommended that we screen imipramine as it is rather close to chlorpromazine:
https://www.sigmaaldrich.com/catalog/product/sigma/i7379?lang=en&region=US

Analogues of imipramine can easily be made from cheap as chips precursors (SA sells the tricyclic ring system for 96 US cents a gram at 97% purity Aldrich I1308 )
![c_swain2](https://user-images.githubusercontent.com/3164942/48722361-d059ec80-ebf1-11e8-98a4-e62d1d44c4b8.png)

*Please note that all the commercial suppliers I checked do not appear to have any interesting imipramine analogues so student synthesis would be required* @mattodd

**Comment by mattodd** [comment] 2018-11-20 10:26
Might help to ping this to Twitter. Could you formulate a couple of tweets that succinctly capture a little of the physical resources we're looking for here (with links pointing here) and tag MycetOS so that it's easy to retweet? This is a first step (of n) whenever the consortium needs something.

**Comment by MFernflower** [comment] 2018-11-22 05:47
@wwjvdsande would you happen to have chlorpromazine and imipramine on hand in order to screen them against madurella?

**Comment by wwjvdsande** [comment] 2018-11-22 08:04
We are a university hosptial imipramine we have in dragee formulation. We also have chlorpormazine HCl and levopromazine. I will have to obtain them from the hospital pharmacy I don't have the pure compounds.

**Comment by MFernflower** [comment] 2018-11-22 10:45
All three would be fantastic provided the addtives do not interfere with the assay
@wwjvdsande

**Comment by drc007** [comment] 2018-11-22 10:48
To get interpretable results it would be much better to isolate and test the active component.

**Comment by MFernflower** [comment] 2018-11-22 10:49
Hence my concern about the additives 

Those three molecules would be perfect as a preliminary screen however

**Comment by wwjvdsande** [comment] 2018-11-22 10:54
I m a microbiologists I will not be able to isolate the active compound from the rest

**Comment by MFernflower** [comment] 2018-11-22 10:56
Would your lab be able to order some chlorpromazine and imipramine from a chemical suppiler? @wwjvdsande

**Comment by drc007** [comment] 2018-11-22 10:58
Make sure you are licensed to order, we don't want to get you in trouble with the authorities.

**Comment by wwjvdsande** [comment] 2018-11-22 11:30
I will check. At the pharmacy they have chlorpromazine HCl without additives. Would that be an option. It is a salt but it will at least be soluble.

**Comment by MFernflower** [comment] 2018-11-22 11:32
I assume that would be fine provided we factor out the weight of the hcl in the final MIC's

Correct me if I am wrong @drc007 @mattodd

**Comment by mattodd** [comment] 2018-11-22 13:43
I wonder if samples of such things is something @bendndi might be able to help us with? I can also tweet out to see if there are supplies anywhere. Chlorpromazine and imipramine. A few mg of each API.

**Comment by MFernflower** [comment] 2018-11-22 13:56
Sigma Aldritch sells both @mattodd

**Comment by MFernflower** [comment] 2018-11-23 14:36
@wwjvdsande slightly unrelated but what is the doubling time of Madurella?
If my hunch is correct phenothiazines will attack the cell during division

**Comment by wwjvdsande** [comment] 2018-11-23 14:39
@MFernflower. I don't know the doubling time of Madurella mycetomatis. I don't think anyone determined that, at least not in the medium I'm using. Typically Madurella mycetomatis in vitro susceptibility tests take a week. It will be in log-phase after 48h. When using alamar blue you see the colour conversion starting by that time.

**Comment by wwjvdsande** [comment] 2018-11-23 14:39
In general Madurella mycetomatis grows relatively slow

**Comment by MFernflower** [comment] 2018-11-23 15:03
Have you the chlorpromazine from the pharmacy to do an inital screen? @wwjvdsande

**Comment by wwjvdsande** [comment] 2018-11-23 15:12
I can obtain it next week. In literature it is known that it can inhibit other filamentous fungi, although at somewhat higher concentrations (40 ug/ml). So I assume it will be active against M. mycetomatis if I test in the same range.

**Comment by MFernflower** [comment] 2018-11-25 05:22
If you can order from combiblocks they have this interesting molecule:
Catalog No. 	QW-9670
@wwjvdsande

**Comment by wwjvdsande** [comment] 2018-11-26 07:21
Sorry, we don't have an account on combiblocks. Today i will see if I can obtain chlorpromazine from the apothecary. If I can obtain a little from them I might be able to include it with the MICs sceduled for the end of the week. Due to the long culture times it will take another week before I know the result though.

**Comment by wwjvdsande** [comment] 2018-11-26 15:26
I will receive the chlorpromazine tomorrow. Just wondering does methylene blue also belonging to this category of molecules? https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Methylene_blue-2d-skeletal.svg/220px-Methylene_blue-2d-skeletal.svg.png
If so I have tested methylene blue before and I know it has some activity against Madurella mycetomatis using PDT.

**Comment by MFernflower** [comment] 2018-11-26 15:36
Technically it does belong to that class but MB is quite promiscuous even
when compared to chlorpromazine ---- I recall my dad used to use it as an antiprotozoal for his freshwater
aquarium and marvelling at how blue it made the water @wwjvdsande

**Comment by MFernflower** [comment] 2018-11-26 18:10
@mattodd once we get mic for chlorpromazine and imipramine how difficult would it be to get somebody at your university to synthesize some n-alkyls of the two ring systems?

Should be easy as ring system + toluene + alkyl bromide

**Comment by wwjvdsande** [comment] 2018-11-27 11:11
I just received the chlorpromazine. Unfortunately it has some sodiumpyrosulphite added to it. It was the only one I could obtain internally. I will set up an MIC. According to literature aspergillus has an MIC around 64 ug/ml, which is higher than the 100 uM we usually start for testing. Therefore I will start with 400 uM (equivalent to 142 ug/ml) and see if it inhibits.

**Comment by drc007** [comment] 2018-11-27 11:37
I think sodium sulphite is used as an anti-fungal.

**Comment by drc007** [comment] 2018-11-27 11:38
> @mattodd once we get mic for chlorpromazine and imipramine how difficult would it be to get somebody at your university to synthesize some n-alkyls of the two ring systems?
> 
> Should be easy as ring system + toluene + alkyl bromide in a stoppered flask with gentle heating

I don't think heating a stoppered flask is a good idea!

**Comment by MFernflower** [comment] 2018-11-27 14:13
^
Oh dear that is what sleep deprivation does to you!  @drc007

**Comment by MFernflower** [comment] 2018-11-27 17:09
Do we know the concentration of pyrosulfite in the chlorpromazine hcl powder? 

 **sodium pyrosulfite (E223) is used as an antifungal preservative in certain processed foods**  

@wwjvdsande

**Comment by wwjvdsande** [comment] 2018-11-29 09:56
Sorry, it did not say the concentration at the ampule. That's annoying. I will see if I can find out at the apothecary itself. It should be noted somewhere I guess.

**Comment by MFernflower** [comment] 2018-12-11 02:13
@wwjvdsande Just wanted to check in - Are you allowed to order from Sigma-Aldrich or will we need a third party to send you 15mg samples of pure imipramine and chlorpromazine?

**Comment by wwjvdsande** [comment] 2018-12-11 07:22
I have to check for the costs to see if i can order it. This week I will know what the chlorpromazine from the pharmacy did. If there is activity it is of course not conclusive as it can have been also from the additives. However if there is no activity it might not be necessary to order chlorpromazine than we might need to focus on the other molecules may be imipramine.

**Comment by MFernflower** [comment] 2018-12-15 01:41
@wwjvdsande @mattodd Working out the prices from Sigma Aldrich NL it appears that the imipramine will be around 128 euro for 5 grams of HCL salt at 99% purity and chlorpromazine hcl is 113 euro for 5 grams of hcl salt at 98% purity 

https://www.sigmaaldrich.com/catalog/product/sigma/c8138?lang=en&region=NL
https://www.sigmaaldrich.com/catalog/product/sigma/i0899?lang=en&region=NL

I do not know what type of funding is in place for MyOS but hopefully we can work something out!

**Comment by MFernflower** [comment] 2019-01-02 19:11
@wwjvdsande  Just wanted to wish you a happy new year and was wondering if you have gotten test results re the pharmacy chlorpromazine

**Comment by wwjvdsande** [comment] 2019-02-07 10:44
@MFernflower a good new year for you too. Sorry for the late reply. We got the results before christmas. M. mycetomatis was sensistive to the chlorpromazine from the pharmacy. We determined the MIC in triplicate. M. mycetomatis had an MIC of 12.5 uM.

**Comment by MFernflower** [comment] 2019-02-07 14:10
Wonderful - have you gotten acess to pure chlorpromazine yet? @bendndi perhaps you could send some to Wendy's lab? 

@wwjvdsande

**Comment by bendndi** [comment] 2019-02-07 14:31
Not sure we can unfortunately @MFernflower . Were not equipped to handle any chemical samples at DNDi. Would need to find someone with a lab who could order it then send it on, and since it's a restricted / regulated chemical this may not be that easy.

**Comment by mattodd** [comment] 2019-02-07 20:38
We can obviously order and ship chemicals, but I imagine it'd be a lot easier if we could find a chemistry lab in Rotterdam to reduce the need for shipping twice @wwjvdsande ? Anyone we can reach out to? Or universities in Delft/Leiden?

**Comment by wwjvdsande** [comment] 2019-02-25 14:18
@MFernflower @mattodd I found some pure chlorpromazine for 25 euro's I could order that.

**Comment by drc007** [comment] 2019-02-25 14:23
Sounds perfect.

**Comment by MFernflower** [comment] 2019-02-25 15:00
There are some possible concerns with S3 drugs crossing the BBB but screening CPZ would
still be good provided we can deposit IC50's vs mycetoma into a public
database @cdsouthan @drc007 @wwjvdsande

**Comment by cdsouthan** [comment] 2019-02-25 15:15
The project @mattodd   should sign up with  CDD vault pronto https://www.collaborativedrug.com/benefits/ 
Ideally, before we drown in  ChemDraw pictures and Excel sheets  (COI  I am on their SAB)

**Comment by bendndi** [comment] 2019-02-25 15:27
@cdsouthan will CDD allow us to have unlimited open access for free?

If not, I believe the solution to avoiding random chemdraw / excel tsunamis is for everyone to commits to using sd files (free) and datawarrior (also free). But for that to be an option we need to lobby github to allow sd files to be uploaded (.sdf is not currently an accepted extension for github files). With this one little change I think github might actually be the one stop shop for a fully open drug discoevry collaboration.

**Comment by drc007** [comment] 2019-02-25 15:28
@mattodd @cdsouthan CDD vault is not open source and the last time I enquired was a significant expense. Who would fund it?

**Comment by cdsouthan** [comment] 2019-02-25 15:34
Dunno -  but note the value here is more as standardised and robust registration and analysis system.  We can take results out for global surfacing any time (we could check but I think you can switch to public) but the confirmed stuff  should eventually go to PubChem anyway

**Comment by bendndi** [comment] 2019-02-25 15:41
@cdsouthan If we want the robustness of a registration / data handling system DNDi can already offer that for "free" via our Biovia sciencecloud platform (indeed all the data is already on there, as are all the Epichem fenarimol componuds). the problem being that that this is a closed system (i.e. we cannot make it directly accessible to all MycetOS participants in an open format since we pay per license). What we can do is set up an automated data dump which would read out a "free" format (e.g. sd file) on a daily / weekly / monthly basis. If we could upload this master sd file to Github it would remove the need for separated excel / chemdraw images. 
This is very much the way that we manage most of our multi party medchem collaborations, even using the sd file dump for partners who actually have direct access to the database itself - somethimes the sd file is just easier since we can automate the extraction to bring out just the data we want (e.g. using knime)

**Comment by cdsouthan** [comment] 2019-02-25 15:51
Fine, this is the project team on the ground's call.  We have had the same discussions over at OSM Antimalarial for years  but they have in the end always defaulted back to ChemDraw (i.e. dead-ended CDX files)  and Excel, although with some getting through to PubChem via ChEMBL or my own submissions  (this not a criticism but the closer they get to 1000 cpds the noisier it becomes and the more I hope nothing goes badly awry before the papers are finished :)

**Comment by drc007** [comment] 2019-02-25 15:54
Actually OSM uses SMILES and Google sheets. But I take your point.

There is certainly a need for an open source web front-end database solution. I’m working on one in my “spare” time. But it is not ready for use yet.

**Comment by bendndi** [comment] 2019-02-25 15:55
@cdsouthan have OSM malaria been using datawarrior? because in our experience data sets of 1000+ compouds or so are pretty common and not really that noisy if you have the right software  (datawarrior / stardrop / vortex /spotfire) and have the data set properly curated to allow rapid filtering down into sub series.

Only reason I ask about datawarrior is because i continues to surprise me how many med chemists are not aware of it :-)

**Comment by bendndi** [comment] 2019-02-25 15:56
@drc007 an open source clone of CDD / sciencecloud etc would be a huge benefit. I know @mattodd  has been trying to get someone interested in funding such a thing in the past...

**Comment by drc007** [comment] 2019-02-25 16:01
@bendndi @cdsouthan The google sheet give programmatic access.

I've written a couple of python scripts that allow import
[Jupyter notebook](https://www.macinchem.org/reviews/osm/osmipython.php) 
or [Vortex](https://www.macinchem.org/reviews/vortex/tut26/scripting_vortex26.php)

I'm sure they could be modified for Datawarrior but I've never done any scripting for Datawarrior.

**Comment by mattodd** [comment] 2019-02-25 22:29
Yes, DataWarrior is an excellent solution that OSM students use a lot.
Yes we need a better solution to compound management and yes I'd love to work with anyone to create an open version we could all use. Cost, easy access for all and the *longevity of a given solution* are the things that worry me about committing to CDD.
SD files might become acceptable to Github if they are zipped? That solution works for chemdraw files. (note that Chemdraw is used primarily for conveying graphical information, rather than for structural information, as @drc007 mentions). A daily upload of SD to a mirror might work nicely, but I'm not qualified to advise on any aspects of feasibility.
I would not recommend using Excel sheets as the default solution for what we're trying to do, but if they are uploaded to an ELN and accessible to all and adequately cross-referenced then they can at least be pretty easily found and extracted.

**Closed as completed** 2023-10-24 02:03 UTC
Labels: Input needed
